### ISSUE TITLE
IPアドレスが[object Object]になる

### ISSUE THREAD

**Issue by yuta0801** [AutoMinecraftServer/AutoMinecraftServer#2]
upnp.externalIpのcallbackの第二引数がからのobjectになってる模樣。
試しにnat-upnpのバージョンを1.0.0に落としても改善しませんでした。
![image](https://user-images.githubusercontent.com/21266306/37242203-af58046a-24a8-11e8-9a09-7551fa2360cf.png)

**Comment by ghost** [comment]
僕の環境では正常に動作しています、nat-upnpのバージョンも最新です。二重ルーターにしているため環境が特殊なことはありますが...

**Comment by yuta0801** [comment]
試しに以前正しく動作していたバージョンで実行してみても同じような結果になったので、おそらく自身のネット環境の変化が原因でした
